//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RJD_IntangibleValuesAccounting
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountingIntangibleValue
    {
        public int AccountingID { get; set; }
        public int Value { get; set; }
        public System.DateTime Date { get; set; }
        public int DepreciationMethod { get; set; }
        public int DepreciationBill { get; set; }
        public int UsefulLifeOfValue { get; set; }
        public int AccountingResponsible { get; set; }
    
        public virtual Bill Bill { get; set; }
        public virtual MethodDepreciation MethodDepreciation { get; set; }
        public virtual IntangibleValueReceipt IntangibleValueReceipt { get; set; }
        public virtual User User { get; set; }
    }
}
