//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RJD_IntangibleValuesAccounting
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntangibleValueReceipt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IntangibleValueReceipt()
        {
            this.AccountingIntangibleValues = new HashSet<AccountingIntangibleValue>();
        }
    
        public int ValueID { get; set; }
        public string ValueFullName { get; set; }
        public string ValueShortName { get; set; }
        public string ValueCost { get; set; }
        public byte ValueNDSPercent { get; set; }
        public string ValueCostWithNDS { get; set; }
        public int ValueType { get; set; }
        public int ValueCounterAgent { get; set; }
        public System.DateTime ValueDateFrom { get; set; }
        public int ValueReceiptMethod { get; set; }
        public int ValueDepreciationGroup { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountingIntangibleValue> AccountingIntangibleValues { get; set; }
        public virtual CounterAgent CounterAgent { get; set; }
        public virtual DepreciationGroup DepreciationGroup { get; set; }
        public virtual Type Type { get; set; }
        public virtual MethodOfReceipt MethodOfReceipt { get; set; }
    }
}
